---
resource: DOCKER_LINUX_DRIVER
manifest: ubuntu-klocwork.yml
working_dir: ''
env:
  OS_TYPE: ubuntu_20.04
  CCACHE_DIR: "/ccache"
  ENABLE_NONFREE_KERNELS: 'yes'
  JOBS: '20'
  KLOCWORK: "1"
  SYSTEM: "linux/ubuntu"
qb_variable_map:
  build_version: BUILD_VERSION
  component_name: COMPONENT_NAME
  irepo_workspace: WORKSPACE
  parent_build_id: BUILD_ID
  build_number: BUILD_NUMBER
  component_branch: COMPONENT_BRANCH
  component_project: COMPONENT_PROJECT
  kw_configuration_name: KW_PROJECT_BRANCH
  kw_server_license_host: KW_LIC_HOST
  kw_server_license_port: KW_LIC_PORT
  kw_server_url: KW_URL
  workspace_dir: WORKSPACE_DIR
  git_revision: GIT_REVISION
  build_version_suffix: BUILD_VERSION_SUFFIX
types:
  release-ubuntu514:
    env:
      BUILD_TYPE: Release
      OS_TYPE: ubuntu514
    steps:
    - name: kw_remove_buildspec_dir
      command: if [ -d $WORKSPACE_DIR/source/klocwork/kwbuildspec/$KW_PROJECT_BRANCH ]; then rm -fr $WORKSPACE_DIR/source/klocwork/kwbuildspec/$KW_PROJECT_BRANCH; fi
    - name: kw_remove_table_dir
      command: if [ -d $WORKSPACE_DIR/source/klocwork/kwtables/$KW_PROJECT_BRANCH ]; then rm -fr $WORKSPACE_DIR/source/klocwork/kwtables/$KW_PROJECT_BRANCH; fi
    - name: kw_remove_report_dir
      command: if [ -d $WORKSPACE_DIR/source/klocwork/report ]; then rm -fr $WORKSPACE_DIR/source/klocwork/report; fi
    - name: recreate_klocwork_folders
      command: mkdir -p $WORKSPACE_DIR/source/klocwork/kwbuildspec/$KW_PROJECT_BRANCH $WORKSPACE_DIR/source/klocwork/kwtables/$KW_PROJECT_BRANCH $WORKSPACE_DIR/source/klocwork/report/
    - name: recreate_build_dir
      command: rm -rf $WORKSPACE_DIR/source/build && mkdir $WORKSPACE_DIR/source/build
    - name: recreate_test_dir
      command: rm -rf $WORKSPACE_DIR/source/test && mkdir $WORKSPACE_DIR/source/test
    - name: kw scan
      command: ./config/scripts/build_in_docker.sh
    output:
    - destination_dir: "linux/ubuntu"
      file_patterns: '*.html,*.json'
      source_dir: "../klocwork/report"
